### ISSUE TITLE
HW7/stack.py

### ISSUE THREAD

**Issue by TheML9I** [AlinaKozz/HW7#2]
https://github.com/AlinaKozz/HW7/blob/a98b5e141c44b3f4d036f2f6502f8888ca857391/stack.py#L7

Usually, `pop` returns the item, not a stack's state.  It leads to the unclear logic of your program: you have at least two points with `print()` invocation. Think about clear functions. 

https://github.com/AlinaKozz/HW7/blob/a98b5e141c44b3f4d036f2f6502f8888ca857391/stack.py#L3
The slice is redundant. 

https://github.com/AlinaKozz/HW7/blob/a98b5e141c44b3f4d036f2f6502f8888ca857391/stack.py#L22-L25

Do you really need this function?

**Comment by akazyryna** [comment]
@TheML9I It's done, I guess
